// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArCuwnCcWk3yrJrLx-ikaX8NdbgzT8-vE',
    appId: '1:854500194181:web:bc4ee29a7b9b682a86f6ec',
    messagingSenderId: '854500194181',
    projectId: 'epsi-b9121',
    authDomain: 'epsi-b9121.firebaseapp.com',
    storageBucket: 'epsi-b9121.appspot.com',
    measurementId: 'G-21YBHJZTW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb1TpZkfFg7xjA5CxFYxibIzGlsSeTjPw',
    appId: '1:854500194181:android:5101d7fa57b560e286f6ec',
    messagingSenderId: '854500194181',
    projectId: 'epsi-b9121',
    storageBucket: 'epsi-b9121.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASkh_7Qu6N3Vtl2BFPT4turOM7AbKY9dw',
    appId: '1:854500194181:ios:d63de33ab6d4e17386f6ec',
    messagingSenderId: '854500194181',
    projectId: 'epsi-b9121',
    storageBucket: 'epsi-b9121.appspot.com',
    iosClientId: '854500194181-628745gpodqltl870n2q3flj4p7lgppe.apps.googleusercontent.com',
    iosBundleId: 'com.example.epsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASkh_7Qu6N3Vtl2BFPT4turOM7AbKY9dw',
    appId: '1:854500194181:ios:d63de33ab6d4e17386f6ec',
    messagingSenderId: '854500194181',
    projectId: 'epsi-b9121',
    storageBucket: 'epsi-b9121.appspot.com',
    iosClientId: '854500194181-628745gpodqltl870n2q3flj4p7lgppe.apps.googleusercontent.com',
    iosBundleId: 'com.example.epsi',
  );
}
